In [2]:
%matplotlib inline
from pyvista import set_plot_theme
set_plot_theme('document')


Load and Plot from a File
~~~~~~~~~~~~~~~~~~~~~~~~~

Read a dataset from a known file type.


Loading a mesh is trivial - if your data is in one of the many supported
file formats, simply use :func:`pyvista.read` to load your spatially
referneced dataset into a PyVista mesh object.

The following code block uses a built-in example file and displays an
airplane mesh.



In [3]:
# sphinx_gallery_thumbnail_number = 5
import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt

The following code block uses a built-in example
file, displays an airplane mesh and returns the camera's position:



In [4]:
# Get a sample file
filename = examples.planefile
print(filename)

/Users/shua784/anaconda3/envs/vtk_env/lib/python3.7/site-packages/pyvista/examples/airplane.ply


Note the above filename, it's a ``.ply`` file - one of the many supported
formats in PyVista.



In [14]:
mesh = pv.read(filename)
cpos = mesh.plot()

You can also take a screenshot without creating an interactive plot window
using the ``Plotter``:



In [13]:
plotter = pv.Plotter(off_screen=True)
plotter.add_mesh(mesh)
plotter.show(screenshot="myscreenshot.png")

VTK(vtkCocoaRenderWindow, height=400, sizing_mode='stretch_width')

The points from the mesh are directly accessible as a NumPy array:



In [7]:
print(mesh.points)

[[896.994    48.7601   82.2656 ]
 [906.593    48.7601   80.7452 ]
 [907.539    55.4902   83.6581 ]
 ...
 [806.665   627.363     5.11482]
 [806.665   654.432     7.51998]
 [806.665   681.537     9.48744]]


The faces from the mesh are also directly accessible as a NumPy array:



In [8]:
print(mesh.faces.reshape(-1, 4)[:, 1:])

[[   0    1    2]
 [   0    2    3]
 [   4    5    1]
 ...
 [1324 1333 1323]
 [1325 1216 1334]
 [1325 1334 1324]]


Loading other files types is just as easy! Simply pass your file path to the
:func:`pyvista.read` function and that's it!

Here are a few other examples - siply replace ``examples.download_*`` in the
examples below with ``pyvista.read('path/to/you/file.ext')``



Example STL file:



In [9]:
mesh = examples.download_cad_model()
cpos = [(107.0, 68.5, 204.0), (128.0, 86.5, 223.5), (0.45, 0.36, -0.8)]
mesh.plot(cpos=cpos)

VTK(vtkCocoaRenderWindow, height=400, sizing_mode='stretch_width')

Example OBJ file



In [10]:
mesh = examples.download_doorman()
mesh.plot(cpos="xy")

VTK(vtkCocoaRenderWindow, height=400, sizing_mode='stretch_width')

Example BYU file



In [11]:
mesh = examples.download_teapot()
mesh.plot(cpos=[-1, 2, -5], show_edges=True)

VTK(vtkCocoaRenderWindow, height=400, sizing_mode='stretch_width')

Example VTK file



In [12]:
mesh = examples.download_bunny_coarse()
cpos = [(0.2, 0.3, 0.9), (0, 0, 0), (0, 1, 0)]
mesh.plot(cpos=cpos, show_edges=True, color=True)

VTK(vtkCocoaRenderWindow, height=400, sizing_mode='stretch_width')